services:
  db:
    image: postgres:15-alpine
    container_name: gym_db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-amraz}
      POSTGRES_DB: ${DATABASE_NAME:-gym_management}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: gym_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-amraz}@db:5432/${DATABASE_NAME:-gym_management}
      - WPPCONNECT_BASE_URL=http://host.docker.internal:21465
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  postgres_data:
